---
title: "git_01"
author: "Estrella Aguilar "
date: "Spring semester 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
In Harlem’s rhythm, a city heartbeat throbs,  
Where dreams are spun in jazz’s sultry sobs.  
Langston’s pen, a symphony of the streets,  
Telling tales of struggles and heartbeats.  
  
Amidst the jazz, a bluesy train hums,  
Whispers of a city where the spirit strums.  
Raisin in the sun, dreams unfurl,  
A Harlem Renaissance, a cultural swirl.  
  
Jazz notes dance on the pages, alive,  
In Langston’s verse, the soul does thrive.  
A weary blues, a weary day,  
Yet hope persists, it finds its way.  
  
Rivers of words flow, a poetic stream,  
Harlem’s dreamer, in each word, a gleam.  
In every line, a piece of the soul,  
Langston’s legacy, a poetic toll.  
  